### ISSUE TITLE
Trouble with Markdown parsing

### ISSUE THREAD

**Issue by mavam** [supernotes/gatsby-transformer-yaml-plus#1]
I'm having trouble with activating the Markdown parser--nothing happens and the output always begins with `md//...`. How can I debug this?

My `gatsby-config.js`:

```js
module.exports = {
  siteMetadata: {
    title: '...',
  },
  plugins: [
    'gatsby-plugin-react-helmet',
    'gatsby-plugin-less',
    {
      resolve: `gatsby-transformer-yaml-plus`,
      options: {
        enableRemark: false,
        markdownPreface: `md//`,
      }
    },
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        path: './src/data/',
      },
    },
  ],
}
```

I've tried all sorts of tweaks: changing `enableRemark`, changing `markdownPreface`, removing the options section entirely. Nothing works. Here's an example of a `foo.yaml`:

```yaml
x: md//This *should* work, but **it doesn't**.
y: >-
  md//Paragraph `1`

  Paragraph *2*

  Paragraph **3**
```

I'm not using GraphQL, because it's overkill for my use case. Instead, my JSX looks like this:

```js
import foo from '../data/foo.yaml'

const Test = () => (
  <div>
  {foo.x}
  {foo.y}
  </div>
)
```

**Comment by connebs** [comment]
As with any other `gatsby-transformer-X` plugin, if you don't utilize Gatsby's "data layer" (i.e. GraphQL + extra goodies) you will not be able to use the transformer plugin. [Please see here for more details.](https://www.gatsbyjs.org/docs/using-gatsby-without-graphql/#the-tradeoffs-of-foregoing-gatsbys-data-layer)

**However**, this reality bummed me out when I first started using Gatsby too, so if you would like to dig deeper into this and find a way to allow for robust / elegant data transformation *without* the data layer, I would definitely consider merging a pull request to add such behavior. That being said, it would probably be better to just create a separate library to achieve your purpose at that point (for better separation of concerns).

I'll leave this open for now as I think it would be good to have a discussion here, so please leave updates if you find a solution to your problem. Getting Markdown to play well with Gatsby can be surprisingly painful sometimes (hence the existence of this lib) so it's always good to hear about more potential solutions!

**Comment by mavam** [comment]
I was afraid that this is the answer. Thanks for laying the problem out clearly. I will have to bite the bullet and use GraphQL, because I lack the cycles to perform any heavy lifting. If I come across a solution or additional insight, I'll be in touch here.
